In [5]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [6]:
print (arr1[2])

3


In [7]:
arr1[2]=5
arr1

array([1, 2, 5])

## 

In [10]:
arr2=np.array([[1,2,3],[3,4,5]])
arr2


array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
arr2[1][2]

5

In [12]:
print(arr2.shape)

(2, 3)


In [13]:
arr2[1][-1]

5

In [14]:
arrS=np.array(['India','USA', 'France', 'Israel'])
arrS

array(['India', 'USA', 'France', 'Israel'], dtype='<U6')

In [15]:
arrR=np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arrL= np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
arr=np.random.rand(10)
arr

array([0.88287887, 0.15394819, 0.07388033, 0.0025407 , 0.38752847,
       0.21900417, 0.63175433, 0.72769949, 0.923725  , 0.44630271])

In [18]:
arr=np.random.rand(3,4)
arr

array([[0.55207977, 0.4945362 , 0.73716154, 0.3638149 ],
       [0.81805186, 0.78059158, 0.29150007, 0.56941112],
       [0.95948674, 0.49496413, 0.50166422, 0.12282925]])

In [20]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
print(np.ones((10,10)))
      

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [24]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [25]:
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
arr=np.random.rand(5,5)

In [29]:
arr

array([[0.98517279, 0.07152654, 0.07245944, 0.30315788, 0.04549581],
       [0.87267474, 0.14514077, 0.28067291, 0.72791461, 0.08512718],
       [0.68521674, 0.39278106, 0.63246371, 0.3337567 , 0.2630348 ],
       [0.62650312, 0.83928136, 0.8866688 , 0.55931414, 0.1635691 ],
       [0.54444884, 0.18533192, 0.6934353 , 0.56445837, 0.50281011]])

In [30]:
np.diag(arr)

array([0.98517279, 0.14514077, 0.63246371, 0.55931414, 0.50281011])

In [31]:
arr.size

25

In [32]:
arr.shape

(5, 5)

In [33]:
np.random.randint(-10,10,4)

array([-7, -6,  6, -4])

In [34]:
arr+10

array([[10.98517279, 10.07152654, 10.07245944, 10.30315788, 10.04549581],
       [10.87267474, 10.14514077, 10.28067291, 10.72791461, 10.08512718],
       [10.68521674, 10.39278106, 10.63246371, 10.3337567 , 10.2630348 ],
       [10.62650312, 10.83928136, 10.8866688 , 10.55931414, 10.1635691 ],
       [10.54444884, 10.18533192, 10.6934353 , 10.56445837, 10.50281011]])

In [35]:
arr/2

array([[0.4925864 , 0.03576327, 0.03622972, 0.15157894, 0.0227479 ],
       [0.43633737, 0.07257038, 0.14033645, 0.3639573 , 0.04256359],
       [0.34260837, 0.19639053, 0.31623186, 0.16687835, 0.1315174 ],
       [0.31325156, 0.41964068, 0.4433344 , 0.27965707, 0.08178455],
       [0.27222442, 0.09266596, 0.34671765, 0.28222919, 0.25140506]])

In [36]:
np.exp(arr)

array([[2.67827463, 1.07414666, 1.07514919, 1.35412824, 1.04654662],
       [2.39330377, 1.15620231, 1.32402045, 2.07075776, 1.08885554],
       [1.98420185, 1.48109408, 1.88224218, 1.39620341, 1.30087198],
       [1.87105626, 2.31470294, 2.42703125, 1.74947219, 1.17770673],
       [1.7236581 , 1.20361787, 2.00057632, 1.75849508, 1.65336088]])

In [37]:
arr

array([[0.98517279, 0.07152654, 0.07245944, 0.30315788, 0.04549581],
       [0.87267474, 0.14514077, 0.28067291, 0.72791461, 0.08512718],
       [0.68521674, 0.39278106, 0.63246371, 0.3337567 , 0.2630348 ],
       [0.62650312, 0.83928136, 0.8866688 , 0.55931414, 0.1635691 ],
       [0.54444884, 0.18533192, 0.6934353 , 0.56445837, 0.50281011]])

In [39]:
np.log10(arr)

array([[-0.00648759, -1.14553275, -1.13990505, -0.51833114, -1.34202862],
       [-0.05914759, -0.83821059, -0.55179951, -0.13791956, -1.06993173],
       [-0.16417203, -0.40584947, -0.19896439, -0.47657001, -0.5799868 ],
       [-0.20307676, -0.07609242, -0.05223857, -0.2523442 , -0.78629873],
       [-0.26404293, -0.73204978, -0.15899405, -0.24836808, -0.298596  ]])

In [40]:
np.sin(arr)

array([[0.83336761, 0.07146557, 0.07239605, 0.29853556, 0.04548011],
       [0.76605095, 0.14463172, 0.27700229, 0.66531421, 0.08502441],
       [0.63284085, 0.38275917, 0.59113372, 0.32759473, 0.26001216],
       [0.58631558, 0.74416326, 0.77497074, 0.53060497, 0.1628407 ],
       [0.5179467 , 0.18427278, 0.63918288, 0.53495829, 0.48188975]])

In [42]:
np.tan(arr)

array([[1.50775968, 0.07164877, 0.07258652, 0.3127997 , 0.04552722],
       [1.19177808, 0.1461686 , 0.28828301, 0.89116898, 0.08533341],
       [0.81732615, 0.4143096 , 0.73289497, 0.34672774, 0.26927374],
       [0.72377247, 1.11402056, 1.22622514, 0.62599449, 0.16504364],
       [0.60549321, 0.1874834 , 0.83112791, 0.63317779, 0.54995689]])

In [43]:
arr

array([[0.98517279, 0.07152654, 0.07245944, 0.30315788, 0.04549581],
       [0.87267474, 0.14514077, 0.28067291, 0.72791461, 0.08512718],
       [0.68521674, 0.39278106, 0.63246371, 0.3337567 , 0.2630348 ],
       [0.62650312, 0.83928136, 0.8866688 , 0.55931414, 0.1635691 ],
       [0.54444884, 0.18533192, 0.6934353 , 0.56445837, 0.50281011]])

In [44]:
np.sum(arr)

11.46241673098673

In [45]:
np.sum(arr ,axis=0)

array([3.71401623, 1.63406164, 2.56570016, 2.4886017 , 1.060037  ])

In [46]:
np.sum(arr,axis=1)

array([1.47781246, 2.11153021, 2.30725301, 3.07533652, 2.49048454])

In [47]:
np.min(arr)

0.04549580816096077

In [48]:
np.max(arr, axis=1)

array([0.98517279, 0.87267474, 0.68521674, 0.8866688 , 0.6934353 ])

In [49]:
np.mean(arr)

0.4584966692394692

In [50]:
np.mean(arr,axis=0)

array([0.74280325, 0.32681233, 0.51314003, 0.49772034, 0.2120074 ])

In [51]:
np.median(arr,axis=0)

array([0.68521674, 0.18533192, 0.63246371, 0.55931414, 0.1635691 ])

In [52]:
np.std(arr,axis=0)

array([0.16235517, 0.27754945, 0.29479098, 0.15872983, 0.163304  ])

In [53]:
np.var(arr)

0.08112206426272174

In [54]:
arr[1:,2:3]

array([[0.28067291],
       [0.63246371],
       [0.8866688 ],
       [0.6934353 ]])

In [55]:
np.sort(arr,axis=1)

array([[0.04549581, 0.07152654, 0.07245944, 0.30315788, 0.98517279],
       [0.08512718, 0.14514077, 0.28067291, 0.72791461, 0.87267474],
       [0.2630348 , 0.3337567 , 0.39278106, 0.63246371, 0.68521674],
       [0.1635691 , 0.55931414, 0.62650312, 0.83928136, 0.8866688 ],
       [0.18533192, 0.50281011, 0.54444884, 0.56445837, 0.6934353 ]])

In [56]:
np.sort(arr)

array([[0.04549581, 0.07152654, 0.07245944, 0.30315788, 0.98517279],
       [0.08512718, 0.14514077, 0.28067291, 0.72791461, 0.87267474],
       [0.2630348 , 0.3337567 , 0.39278106, 0.63246371, 0.68521674],
       [0.1635691 , 0.55931414, 0.62650312, 0.83928136, 0.8866688 ],
       [0.18533192, 0.50281011, 0.54444884, 0.56445837, 0.6934353 ]])

In [57]:
arr.T

array([[0.98517279, 0.87267474, 0.68521674, 0.62650312, 0.54444884],
       [0.07152654, 0.14514077, 0.39278106, 0.83928136, 0.18533192],
       [0.07245944, 0.28067291, 0.63246371, 0.8866688 , 0.6934353 ],
       [0.30315788, 0.72791461, 0.3337567 , 0.55931414, 0.56445837],
       [0.04549581, 0.08512718, 0.2630348 , 0.1635691 , 0.50281011]])

In [58]:
arr[:3,:].T

array([[0.98517279, 0.87267474, 0.68521674],
       [0.07152654, 0.14514077, 0.39278106],
       [0.07245944, 0.28067291, 0.63246371],
       [0.30315788, 0.72791461, 0.3337567 ],
       [0.04549581, 0.08512718, 0.2630348 ]])

In [62]:
arr=np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [63]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [64]:
print(arr1)

[4 5 6 7 8 8]


In [66]:
arr2=np.insert(arr,-0,[1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
arr3=np.delete(arr2,0)

In [70]:
arr3

array([2, 3, 4, 5, 6, 7, 8])

In [7]:
arr3=np.delete(arr2,[1,3])
arr3

array([5, 7, 5, 6, 7, 8])

In [72]:
print(arr3)

[1 3 5 6 7 8]


In [73]:
arrC = arr3.copy()
arrC

array([1, 3, 5, 6, 7, 8])

In [6]:
arr1= np.array([[1,2,3,4],[1,2,3,4]])
arr2= np.array([[5,6,7,8],[5,6,7,8]])
cat = np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [77]:
arr2.shape

(2, 4)